### ISSUE TITLE
Créer install_db

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/Nomenclature-api-module#10]
Créer un ``install_db.sh`` avec un paramètre dans le ``settings.ini`` permettant de choisir si on installe la partie taxonomie (``cor_taxref_nomenclature``) ou non.

**Comment by bouttier** [comment]
Pour le moment, j’ai créé une unique branche `alembic` (je ne parle pas de la branche git mais bien de la [fonctionnalité d’`alembic`](https://alembic.sqlalchemy.org/en/latest/branches.html)) nommée `ref_nomenclatures` avec 2 migrations : une première qui crée le schéma de nomenclature, et une deuxième qui crée le schéma pour la partie taxonomie.

Je propose d’associer ces deux migrations à 2 branches distincts : `ref_nomenclatures` et `ref_nomenclatures_taxonomie`. Il sera alors possible avec les commandes standards d’`alembic` de choisir d’installer la partie taxonomie ou non.

**Comment by bouttier** [comment]
Géré via alembic
