### ISSUE TITLE
Data nomenclatures - Format des dates de création/MAJ

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/Nomenclature-api-module#32]
Il y a 2 formats de dates dans le fichier SQL de création des nomenclatures par défaut : https://github.com/PnX-SI/Nomenclature-api-module/blob/develop/data/data_nomenclatures.sql

2018-05-14 et 09/05/2018 sur la fin (habitats...). A homogénéiser je pense.

Se pose même la question d'insérer des dates pour les nomenclatures ou de laisser now() par défaut. Cela dépend si on veut insérer la date où on a ajouté ces nomenclatures dans le projet GeoNature, ou alors la date où ces nomenclatures ont été intégrées dans la BDD d'une instance GeoNature.

**Comment by camillemonchicourt** [comment]
Au départ les dates étaient au format yyyy-mm-dd. A homogénéiser je pense car sur la deuxième partie des nomenclatures, elle est de type dd/mm/yyyy.
Pour les types de nomenclatures, la date insérée semble correspondre à la date de mise à jour au niveau du SINP (http://standards-sinp.mnhn.fr/nomenclature/).
Pour les nomenclatures, la date semble correspondre à leur intégration dans GeoNature.
A mettre en cohérence aussi ?

**Comment by camillemonchicourt** [comment]
OK fait pour l'insertion des types de nomenclatures et des nomenclatures. On prend les dates de création et de mises de références, fournies par la structure qui gère les nomenclatures (SINP dans la plupart des cas), sous la forme ``yyyy-mm-dd``.
Pas fait en UPDATE, mais ça serait un peu lourd, et pas essentiel ?

**Comment by TheoLechemia** [comment]
Oui vraiment lourd et pas essentiel.

**Comment by camillemonchicourt** [comment]
Corrigé dans 1.3.3
