### ISSUE TITLE
Révision des nomenclatures de sensibilité

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/Nomenclature-api-module#39]
Dans la version 1.3.5 du sous-module de nomenclatures, les intitulés de la nomenclature des NIVEAUX DE SENSIBILITE ont été revus, en accord avec @jpanijel, même si ils n'ont pas encore évolué au niveau du SINP : https://github.com/PnX-SI/Nomenclature-api-module/commit/d8fba8a8f7ec4141b954cda45ce5b899fdc32fa5
On a volontairement pris les devants car les intitulés de la nomenclature SINP actuels n'étaient pas clairs ni cohérents.

**Comment by camillemonchicourt** [comment]
Mais pour être encore plus clair et cohérent, et réduire les confusions avec les nomenclatures de niveau de diffusion, je propose de les renommer en parlant avant tout de sensibilité : https://github.com/PnX-SI/Nomenclature-api-module/pull/41/files
Ok pour toi @jpanijel ?

**Comment by jpanijel** [comment]
Ok pour moi
