### ISSUE TITLE
cor_nomenclature_sensitivity

### ISSUE THREAD

**Issue by joelclems** [PnX-SI/Nomenclature-api-module#44]
Est ce que la table `ref_nomenclatures.calculate_sensitivity` est toujours utilisée?

On la retrouve dans la fonction `ref_nomenclatures.calculate_sensitivity`

https://github.com/PnX-SI/Nomenclature-api-module/blob/8724060da1400cd69a0423ab919f0aaa18bb0cdf/data/nomenclatures_taxonomie.sql#L94

qui apparrement n'est plus utilisée dans geonature (commentée dans occtax)

https://github.com/PnX-SI/GeoNature/blob/00489e8c8d4f9346ac1536b8e22c648be95848da/contrib/occtax/data/occtax.sql#L642

y a t'il d'autres utilisations ?

**Comment by TheoLechemia** [comment]
Non pas d'utilisation à ma connaissance. Tout à été basculé dans `gn_sensitivity`

**Comment by bouttier** [comment]
Obsolète
