### ISSUE TITLE
Gestion des conflits de nomenclature

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/Nomenclature-api-module#9]
"Les BDD relationnelles, c'est pas fait pour le partage".

On fournit par défaut des nomenclatures standard pour les modules de base. 
Le principe est que chacun puisse compléter ces nomenclatures, voire en créer de nouvelles pour ses modules spécifiques locaux. 

Dans ce cas, comment gérer les potentiels conflits de nomenclatures...
Les ID sont des serials...

1. Maintenir un référentiel global de nomenclatures
2. Mettre en place un mécanisme de surcouche des nomenclatures
3. Utiliser les codes plutôt que les ID
4. Créer des fonctions de génération des contraintes
5. Clé code nomenclature + code type nomenclature
6. Remplacer les FK par des contraintes Check
7. Utiliser des UUID

On retient les points 3, 5 et 6.

On utilise : 

- On stocke les codes dans la Synthese
- On stocke les ID nomenclatures dans les schémas des modules des protocoles (pour garantir l'intégrité référentielle des UPDATE CASCADE) mais en faisant des check sur les codes
- Le code Python et JS se base uniquement sur les codes
- Ainsi les ID ne sont nul part (ni SQL, ni Py, ni Js)

Conséquences : 

- Modifier BDD Nomenclatures et rapatrier SQL dans son dépôt (https://github.com/PnX-SI/Nomenclature-api-module/issues/3)
- Modifier les correspondances Nomenclatures / Taxonomie (en profiter pour les migrer dans le schéma ``taxonomie``, voir https://github.com/PnX-SI/GeoNature/issues/384)
- Réécrire API Nomenclature
- Modifier code OccTax (composants notamment) et sa BDD
- Scripts MAJ BDD

**Comment by camillemonchicourt** [comment]
2 questions se posent : 

- Quand on insère les nomenclatures dans la BDD, on n'insère plus les ID, on laisse le serial faire ?
- Du coup, ça veut dire qu'on ne peut pas insérer de jeux de données Tests car on n'est pas sur des id des nomenclatures
- Que faire avec la table ``taxonomie.cor_taxref_nomenclature`` et ``taxonomie.cor_taxref_sensitivity`` qui utilisent les ID des nomenclatures en clé étrangères. Si on passe sur les codes des nomenclatures, alors ils ne feront plus référence à des clés primaires.

**Comment by camillemonchicourt** [comment]
Voir les commits dans la branche dédiée : https://github.com/PnX-SI/GeoNature/commits/evol_nomenclatures

Côté Front : https://github.com/PnX-SI/GeoNature/commit/64a8ac7c062271c89ed0ebe1532f636aeedbf87b

SQL : 
- https://github.com/PnX-SI/GeoNature/commit/d93b5e4504b37a5904c1d95cba1c184c5a89dda2
- https://github.com/PnX-SI/GeoNature/commit/fa4fe175b158d9bbffe464f950606f5ba2dcdcb1
- https://github.com/PnX-SI/GeoNature/commit/434406984f35d4139a3155300e951d737b24a67f
- https://github.com/PnX-SI/GeoNature/commit/6738d9291ad81de83eafdb96e0935250d1c6e234
- https://github.com/PnX-SI/GeoNature/commit/598b2f50039a7a5303905a3a2220ae10e1401a19
- https://github.com/PnX-SI/GeoNature/commit/e8cbb493c211407f49b081dc1f82333d097bb5a0
- https://github.com/PnX-SI/GeoNature/commit/849fc070574bc12a37711b14c5231571de6e2901
- https://github.com/PnX-SI/GeoNature/commit/35a19957ff6658ca7b047b28a67aea5f56cb3d34

DONE : 
- Modif de ref_nomenclatures et de pr_occtax
- Suppression des id_type en dur dès que possible.
- Modif aussi de default_nomenclatures_values dans les 2 schémas
- Modif des functions
- Modif des inserts

**Comment by camillemonchicourt** [comment]
Pour voir tous les changements réalisés : https://github.com/PnX-SI/GeoNature/compare/develop...evol_nomenclatures

Pour la problématique de gestion des scripts d'insertion dont on ne maitrise plus les id_nomenclatures : 
- En effet on n'insère plus les ``id_nomenclature``, on laisse les serial les gérer
- Unicité code_nomenclature + code_type_nomenclature
- On met des SELECT sur nos insert qui récupère l'id_nomenclature à partir du couple code_nomenclature + code_type_nomenclature (à partir d'une fonction dédiée)
- On garde bien la FK sur le id_nomenclature

**Comment by TheoLechemia** [comment]
Scripts d'update : 

- https://github.com/PnX-SI/GeoNature/commit/0bddd65824e48296b07db2a482588228b51b1dd8
- https://github.com/PnX-SI/GeoNature/commit/671680e84838d0fa5af691f852acf0040f028be0

**Comment by amandine-sahl** [comment]
* https://github.com/PnX-SI/GeoNature/commit/09cdb652def1c6df9b15557a4fe03576adc67e0c
* https://github.com/PnX-SI/GeoNature/commit/fdc14797991cb66971494d9e80b90f86863c43f7
